name: money_mind
description: "A new Flutter project."
publish_to: "none"
version: 0.1.0

environment:
  sdk: ^3.5.0

dependencies:
  flutter:
    sdk: flutter
  flutter_svg: ^2.0.16
  sqflite: ^2.0.0+4 # Check for the latest version
  path: ^1.8.0 # Required for file path management
  intl: ^0.20.1
  math_expressions: ^2.2.0
  fl_chart: ^0.70.2
  tab_container: ^3.5.3 # tab_container package for tab management

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^4.0.0

flutter:
  uses-material-design: true

  assets:
    - assets/icons/
    - assets/images/
